exports.victims = [
  { name: 'Mitchio' },
  { name: 'Joanna' },
  { name: 'Lucianna' },
  { name: 'Mitchio' },
  { name: 'Joanna' },
  { name: 'Lucianna' },
  { name: 'Mitchio' },
  { name: 'Joanna' },
  { name: 'Lucianna' },
  { name: 'Mitchio' },
  { name: 'Joanna' },
  { name: 'Lucianna' },
  { name: 'Mitchio' },
  { name: 'Joanna' },
  { name: 'Lucianna' },
];
